### ISSUE TITLE
Unable to resolve "React" from "node_modules\@react-native-community\checkbox\js\CheckBox.android.js"

### ISSUE THREAD

**Issue by EmmanuelLV** [react-native-community/react-native-checkbox#16]
# Bug
I can't use it after install it with 
npm install @react-native-community/checkbox --save
inside expo project

## Environment info

expo 3.0.4 windows user 

## Steps To Reproduce

1.install
2.Import
3.expo start

**Comment by nicholaslee119** [comment]
Thanks for your report, Could you please tell me what version of React-Native did you use?

**Comment by serggin** [comment]
Problem in case sensitive imports like
require('React'), require('StyleSheet').
Must be require('react'), etc ...
It cases errors in case sensitive UNIX-like file system

**Comment by Hexor** [comment]
> @EmmanuelLV
> Thanks for your report, Could you please tell me what version of React-Native did you use?

using 0.60.3 facing this problem.

**Comment by nicholaslee119** [comment]
@Hexor 
we will release a new version for supporting RN 0.60.0 in a few days

**Comment by azlogs** [comment]
I got the same problem with RN 0.60.3. Have you fixed it yet? @nicholaslee119

**Comment by nicholaslee119** [comment]
@azlogs @Hexor 
0.2.0 was just published, please check it!
