### ISSUE TITLE
Unable to resolve module 'Unimplemented View' from '.../@react-native-community/checkbox/js/CheckBox.ios.js'

### ISSUE THREAD

**Issue by Tommoore96** [react-native-community/react-native-checkbox#17]
# Bug

![Simulator Screen Shot - iPhone X - 2019-07-30 at 08 41 12](https://user-images.githubusercontent.com/27972790/62110309-0df53600-b2a6-11e9-80d0-5aca86df55ec.png)

Appears when adding the the `react-native-community/checkbox` to my project.

I've tried linking and unlinking (as I believe react-native ^0.60 autolinks anyway).

## Environment info

System:
    OS: macOS 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 22.41 MB / 8.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.4.0 - /usr/local/bin/node
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    Android SDK:
      API Levels: 27, 28, 29
      Build Tools: 28.0.3, 29.0.0
      System Images: android-29 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: ^16.8.3 => 16.8.3
    react-native: ^0.60.4 => 0.60.4
  npmGlobalPackages:
    react-native-cli: 2.0.1

**Comment by nicholaslee119** [comment]
CheckBox doesn't support iOS. Please use Switch for iOS.
Thanks
