### ISSUE TITLE
Faults and Errors in the Manual

### ISSUE THREAD

**Issue by serggin** [react-native-community/react-native-checkbox#18]
# Bug

Section "Manual installation" 
1) android/settings.gradle: 
project(':@react-native-community/checkbox') ...
Graddle 5 doesn't allows "/" in project name. 
Easy workaround: ":@react-native-community-checkbox" or any similar text
2) android/app/src/main/.../MainApplication.java
Error in import statement. Should be:
import com.reactnativecommunity.checkbox.ReactCheckBoxPackage;
Error in package name, should be:
new ReactCheckBoxPackage()

## Environment info

Gradle 5

**Comment by nicholaslee119** [comment]
Thanks for your report, I have already fixed the section of Manual installation. Check it, please.
