### ISSUE TITLE
No podspec found

### ISSUE THREAD

**Issue by rcpassos** [react-native-community/react-native-checkbox#20]
# Bug

After run `yarn add @react-native-community/checkbox`

I had run `pod install` inside the ios folder, but I'm getting this error:

[!] No podspec found for `@react-native-community` in `../node_modules/@react-native-community/checkbox`

## Environment info

React native info output:

```bash
 System:
    OS: macOS 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Memory: 47.00 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.9.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.10.3 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.5 => 0.60.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

Library version: ^0.2.0

## Steps To Reproduce

1.  run `yarn add @react-native-community/checkbox`
2. cd ios/
3. pod install

Describe what you expected to happen:

1. pod installation successfully

**Comment by neilgamb** [comment]
Any update on this? Having same issue!

**Comment by SelfDevTV** [comment]
Same Problem here!
I moved to react-native-communtiy because I got this warning while importing checkbox with react-native core and now it's not working, since I can't `pod install`

**Comment by hatlestad** [comment]
As a workaround until this is fixed...

Assuming you are using an icon library (such as react-native-vector-icons), you can make your own checkbox pretty easily.

Use the `boolean value` in the name prop to set the icon's name.
Add your function to `onPress` to have it update the value in state (in my example I am using Hooks, could be easily tweaked for classic state management).

```
<MaterialCommunityIcons
     size={30}
     name={formValues.myCheckbox ? 'checkbox-marked-outline' : 'checkbox-blank-outline'}
     color={'#000000'}
     onPress={() => setFormValues({ ...formValues, myCheckbox: !formValues.myCheckbox })}
/>
```

**Comment by AmmarRajab** [comment]
really , no response !! .. it's really annoying

**Comment by AmmarRajab** [comment]
created a pull request 

https://github.com/react-native-community/react-native-checkbox/pull/23/commits/00203b8847c3c1e7e96646fbaf99aee793061c21

**Comment by nicholaslee119** [comment]
Thanks to @AmmarRajab 's work,
0.2.1 was released
thanks for waiting

**Comment by Naturalclar** [comment]
@nicholaslee119 should this issue be closed? The problem seems to be solved.

**Comment by nicholaslee119** [comment]
sloved

**Comment by NelsonPetitos** [comment]
Still having this Error @react-native-community/checkbox version 0.5.5
