### ISSUE TITLE
Using TintColors

### ISSUE THREAD

**Issue by ocano12** [react-native-community/react-native-checkbox#21]
Hi,

Could I get an elaboration on how the TintColors prop works? using the object shape in the README throws errors. It could be a knowledge gap for me here Is there any example I can follow?

<CheckBox onValueChange={handleCheck} value={check} tintColors={true?: ?'blue, false?: ?'grey'  } />

how im currently using it. I would just like to set the color of when its checked to blue

Thanks for all the help!

**Comment by vonovak** [comment]
hi!
`<CheckBox onValueChange={handleCheck} value={check} tintColors={{ true: 'blue' }} />`

should do the job. Let me know if it doesn't

**Comment by vishalkarmal** [comment]
@vonovak 

> hi!
> `<CheckBox onValueChange={handleCheck} value={check} tintColors={{ true: 'blue' }} />`
> 
> should do the job. Let me know if it doesn't

it's not working

**Comment by Nsingh0007** [comment]
> hi!
> `<CheckBox onValueChange={handleCheck} value={check} tintColors={{ true: 'blue' }} />`
> 
> should do the job. Let me know if it doesn't

It's not working

**Comment by amit13091992** [comment]
> > hi!
> > `<CheckBox onValueChange={handleCheck} value={check} tintColors={{ true: 'blue' }} />`
> > should do the job. Let me know if it doesn't
> 
> It's not working

@Nsingh0007 any workAround or solution for this?

**Comment by Nsingh0007** [comment]
Yes it's not working right now.
Can you help me.

**Comment by Nsingh0007** [comment]
> > > hi!
> > > `<CheckBox onValueChange={handleCheck} value={check} tintColors={{ true: 'blue' }} />`
> > > should do the job. Let me know if it doesn't
> > 
> > 
> > It's not working
> 
> @Nsingh0007 any workAround or solution for this?

NO, i am also looking for the solution for it.

**Comment by vonovak** [comment]
Hi there! Sorry you're having an issue. As the issue template explains, we require that you provide a runnable example that reproduces your issue (see the issue template). The reason is that maintainers do not have time to try reproduce bugs themselves. Please try to minimize the superfluous code and focus only on reproducing the bug.

Please create a new issue with this and we'll be happy to review it!
