### ISSUE TITLE
When will this be published?

### ISSUE THREAD

**Issue by kdawgwilk** [react-native-community/react-native-checkbox#3]
I was trying to use this lib and found that is has not been published yet

**Comment by vonovak** [comment]
In the meantime you can use checkbox from react native directly

**Comment by nicholaslee119** [comment]
@kdawgwilk Sorry for keep you waiting, I am working on it.
just as @vonovak mentioned, you can use the checkbox from react native directly, It would not be removed before this package release

**Comment by mjmasn** [comment]
The deprecation of `CheckBox` from `react-native` + instructions to install `@react-native-community/checkbox` instead is now mentioned in a React Native 0.60.0 yellow box warning. To avoid confusion this needs to be published or the yellow box warning temporarily removed from RN.

**Comment by nicholaslee119** [comment]
@mjmasn thanks for your report, I will publish it as soon as possible

**Comment by nicholaslee119** [comment]
@mjmasn 
https://www.npmjs.com/package/@react-native-community/checkbox
v0.1.0 is published. Please check it, if there is any problem, please let me know

**Comment by rodrigowpl** [comment]
it should be working for ios?

**Comment by nicholaslee119** [comment]
@rodrigowpl 
As discussed in this [issue](https://github.com/facebook/react-native/issues/16537) 
CheckBox doesn't support iOS. Please use Switch for iOS.
Thanks

**Comment by nicholaslee119** [comment]
already published
