### ISSUE TITLE
'BEMCheckBox.h' file not found

### ISSUE THREAD

**Issue by crazypioneer** [react-native-community/react-native-checkbox#50]
I just checked new release for IOS.
Thank you.

Unfortunately, it doesn't work...
I wasted my time...

**Comment by nameEO** [comment]
Add pod 'BEMCheckBox' in your /ios/Podfile file

**Comment by nicholaslee119** [comment]
Sorry for the trouble, A new version was just released to fix this

**Comment by oremlawi** [comment]
Try this:

#import <BEMCheckBox/BEMCheckBox.h>

**Comment by codeion** [comment]
The same issue with v0.5.13

**Comment by hend-elsahli** [comment]
Same issue after installing latest version `0.5.13`

**Comment by FlyingForYouGH** [comment]
I've create new issue here => [https://github.com/react-native-checkbox/react-native-checkbox/issues/182](https://github.com/react-native-checkbox/react-native-checkbox/issues/182)

**Comment by karansodhi** [comment]
add  pod 'BEMCheckBox' to ios/podfile of your project
