### ISSUE TITLE
Cant make it work on iOS

### ISSUE THREAD

**Issue by IlanZ93** [react-native-community/react-native-checkbox#52]
Hello,

I use "import CheckBox from '@react-native-community/checkbox';" for my checkbox on Android, and now that i look for my App on iOS, i cant see the checkbox, i have 0 error on my simulator.

I have followed the instruction : (im on RN > 0.60)

npm install @react-native-community/checkbox --save
and install cocoapods
npx pod-install

I see that for iOS you refered to BEMCheckBox so i check the README and i tried to add "pod 'BEMCheckBox' " to my podfile, but still dont work.

I tried with example code but still dont work here my code : 

`import CheckBox from '@react-native-community/checkbox';`
(...)
```const checkBoxIdExpiry =
    Platform.OS === 'ios' ? (
      <CheckBox
        value={checked}
        onChange={() => unCheckOtherExpiries(idExpiry)}
        lineWidth={2}
        hideBox={false}
        boxType={'circle'}
        tintColor={'#9E663C'}
        onCheckColor={'#6F763F'}
        onFillColor={'#4DABEC'}
        onTintColor={'#F4DCF8'}
        animationDuration={0.5}
        disabled={false}
        onAnimationType={'bounce'}
        offAnimationType={'stroke'}
      />
    ) : (
      <CheckBox
        disabled={false}
        value={checked}
        onChange={() => unCheckOtherExpiries(idExpiry)}
      />
    );
```
(...)

```return( 
      <View style={[contracts.infosView, contracts.flexRow]}>
        {checkBoxIdExpiry}
        <Text style={contracts.label}>{expiryName}</Text>
      </View>```

**Comment by nicholaslee119** [comment]
Sorry for your trouble, could you please answer the next questions to let us help you
1) Did you use the 0.4.1 version? if not please use the current version
2) Where did you use the `npx pod-install`? (please use this under your ios directory not your root directory)

**Comment by IlanZ93** [comment]
Oh ok it's my fault  didnt noticed i was not using the 0.4.1 version. Thought that using "npm install @react-native-community/checkbox --save" will install the latest but i had the 0.3. Its ok now 👍

**Comment by ZainaliSyed** [comment]
<img width="1440" alt="Screenshot 2020-07-19 at 4 06 19 PM" src="https://user-images.githubusercontent.com/24393023/87873384-bbdb8200-c9da-11ea-9c8c-d64bec7db440.png">

I alway gets this error on ios 

iphonesimulator/RNCCheckbox/libRNCCheckbox.a(BEMPathManager.o) 
ld: 38 duplicate symbols for architecture x86_64

**Installation** 
ios dir : npx pod-install
**POD** 
pod 'BEMCheckBox'


"@react-native-community/checkbox": "^0.4.2",
"react-native": "0.62.2",
