### ISSUE TITLE
iOS - Disabled not works

### ISSUE THREAD

**Issue by leocaliban** [react-native-community/react-native-checkbox#56]
# Is there any way to disable on iOS?

I tried to put it inside TouchableOpacity to handle changes and disable it and even then it ignores the disabled={true}

**Comment by nicholaslee119** [comment]
Sorry, `disabled` prop only supported in Android Now.
Actually, it is an issue about the BEMCheckbox which hasn't `disabled` prop.
I am wondering to PR to BEMCheckbox to implement `disabled`, OR implement in JS-level in our `react-native-checkbox`

Or, you could implement this in YOUR JS-level component for now

**Comment by gedeagas** [comment]
Hi @nicholaslee119, i think for now the best option is to implement the disabled props via javascript. i already make a pr for this, kindly check.

**Comment by nicholaslee119** [comment]
0.5.0 was released, disabled was added by @gedeagas

**Comment by victorwvieira** [comment]
Updated to 0.5.0 version and now the props disabled are working on iOS and Android.
