### ISSUE TITLE
Can't get parent to use onStartShouldSetResponderCapture

### ISSUE THREAD

**Issue by fredrikjarnbrost-nordnet** [react-native-community/react-native-checkbox#59]
# Question

Hi, I can't get onStartShouldSetResponderCapture to work with this component.

```
<TouchableOpacity
      onStartShouldSetResponderCapture={() => true}
      onPress={() => console.log('test')}
    >
      <CheckBox onValueChange={this.onPress} value={this.props.checked} width={20} height={20} />
</TouchableOpacity>
```

In the example above I don't get the 'test' log as I expected. Is there a way to do it?

**Comment by nicholaslee119** [comment]
Hmmm, I think it is an issue about TouchableOpacity.
But we would try to reproduce it, and figure it out
