### ISSUE TITLE
Changing box color

### ISSUE THREAD

**Issue by afouchet** [react-native-community/react-native-checkbox#62]
# Feature request

I'd like to change the box color (for my app color scheme, it would be better if the checked box was grey).
I tried to change tintColor, onCheckColor, onFillColor and onTintColor, I still had a green box.

## Why it is needed

An app may have a color scheme where this green doesn't it, and the user would want to change it.

## Possible implementation

Unfortunately, I never did native code, so I can't help with that :-(

### Code sample

Ideally, there'd be a prop "style" or "boxStyle" where we could change parameters

> <CheckBox value={ true} boxStyle={ color: #ffffff } />

**Comment by nicholaslee119** [comment]
tintColor, onCheckColor, onFillColor and onTintColor are only for iOS

For Android, you could use the prop of tintColors to change the color. As you see, the props for Android to customize the Checkbox is not enough. We would consider this in the future version.

**Comment by afouchet** [comment]
Thanks
(it's confusing to have "tintColor" for iOS and "tintColor**s**" for Android :-(

**Comment by SYNTAG** [comment]
@afouchet This works but I can't get the `Checkbox` to accept both true & false styles for `tintColors` on Android. For example if I do just `tintColors={{ true: 'red' }}` then that will make the true state for the checkbox red as intended. However, if I do `tintColors={{ true: 'red' }, { false: 'green' }}` then that will ignore the true color property and only use the false property. I can't get it to use both it's only one or the other.

I am using:
```json
"@react-native-community/checkbox": "^0.5.4"
"react-native": "0.63.2",
```

**Comment by Jeffrey-Dozva** [comment]
hey @afouchet please try using

tintColors={{ true: 'red, false: 'yellow' }}

**Comment by SirajMehmood** [comment]
> hey @afouchet please try using
> 
> tintColors={{ true: 'red, false: 'yellow' }}

works perfectly

**Comment by kasimkazmi** [comment]
tintColors={{ true: 'red', false: 'yellow' }}

Try this -- Working :)

**Comment by MatkoMilic** [comment]
> tintColors={{ true: 'red, false: 'yellow' }}

Thank you!

**Comment by YSKavinda** [comment]
does it support IOS?
