### ISSUE TITLE
Importing react-native-checkbox into react-native-windows project generates a build error

### ISSUE THREAD

**Issue by kmelmon** [react-native-community/react-native-checkbox#74]
This applies only to Windows.  I've tried adding react-native-checkbox to my app by doing the following

1 run react-native init and generate a new project
2 run react-native-windows-init to add Windows support
3 yarn add @react-native-community/checkbox to the project
4 Manually add the checkbox vcxproj to the solution (as of version 62 we don't have auto-linking yet)

This is generating an error when importing the project:

D:\rngallery\node_modules\@react-native-community\checkbox\windows\CheckboxWindows\CheckboxWindows.vcxproj : error  : The imported project "D:\rngallery\node_modules\@react-native-community\node_modules\react-native-windows\Microsoft.ReactNative.Cxx\Microsoft.ReactNative.Cxx.vcxitems" was not found. Confirm that the expression in the Import declaration "..\..\..\node_modules\react-native-windows\Microsoft.ReactNative.Cxx\Microsoft.ReactNative.Cxx.vcxitems" is correct, and that the file exists on disk.  D:\rngallery\node_modules\@react-native-community\checkbox\windows\CheckboxWindows\CheckboxWindows.vcxproj

I tracked this back to this line in the vcxproj for Windows:
https://github.com/react-native-community/react-native-checkbox/blob/756aabc9c37d07c9ed0fc93cf146d4231d8831c8/src/windows/CheckboxWindows/CheckboxWindows.vcxproj#L76

The problem here is the path to the shared project is using a relative path to ..\..\..\node_modules, which assumes react-native-windows is installed at the same directory as the community module, but this isn't the case when react-native-windows is hoisted up to the root.

I chatted with Igor about this, he understands the issue and will submit a fix.

**Comment by kmelmon** [comment]
Note that after hacking my vcxproj to point to the correct location, I hit another build error, due to this line:
https://github.com/react-native-community/react-native-checkbox/blob/756aabc9c37d07c9ed0fc93cf146d4231d8831c8/src/windows/CheckboxWindows/CheckboxWindows.vcxproj#L3

The problem here is similar... it's assuming it can find packages in ..\packages, but this isn't the correct location.

**Comment by nicholaslee119** [comment]
https://github.com/react-native-community/react-native-checkbox/releases/tag/v0.5.1

0.5.1 was just released to fix this bug

**Comment by kmelmon** [comment]
Thanks a bunch!

**Comment by kmelmon** [comment]
Confirmed 0.5.1 works in my project.
