### ISSUE TITLE
checkbox build error in typescript project

### ISSUE THREAD

**Issue by kmelmon** [react-native-community/react-native-checkbox#76]
# Bug report

## Environment info

`react-native info` output:

```bash
D:\rngallery>npx react-native info
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.19041
    CPU: (12) x64 Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
    Memory: 16.22 GB / 31.85 GB
  Binaries:
    Node: 12.16.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.19.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
      Android NDK: 17.2.4988734
  IDEs:
    Android Studio: Version  3.6.0.0 AI-192.7142.36.36.6392135
  Languages:
    Java: Not Found
    Python: 3.8.5 - C:\Python38\python.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: ^0.62.0-0 => 0.62.2
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: x.x.x

## Steps to reproduce

yarn add @react-native-community/checkbox to an existing react-native project
Configure typescript using the standard tsconfig from RN website.  See https://reactnative.dev/docs/typescript
yarn tsc

Describe what you expected to happen:
build should succeed

Instead you get some build errors:
   
node_modules/@react-native-community/checkbox/typings/index.d.ts:3:37 - error TS2307: Cannot find module '../js/CheckBox.android' or its corresponding type declarations.

3 import {Props as AndroidProps} from '../js/CheckBox.android';
                                      ~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@react-native-community/checkbox/typings/index.d.ts:4:33 - error TS2307: Cannot find module '../js/CheckBox.ios' or its corresponding type declarations.

4 import {Props as IOSProps} from '../js/CheckBox.ios';
                                  ~~~~~~~~~~~~~~~~~~~~

node_modules/@react-native-community/checkbox/typings/index.d.ts:5:37 - error TS2307: Cannot find module '../js/CheckBox.windows' or its corresponding type declarations.

5 import {Props as WindowsProps} from '../js/CheckBox.windows';
                                      ~~~~~~~~~~~~~~~~~~~~~~~~

## Reproducible sample code

Clone this repo and switch to the ts branch:
https://github.com/microsoft/RNGallery/tree/ts

**Comment by rectified95** [comment]
@nicholaslee119  FYI There are a few other issues related to broken TS typings - listing them here for reference:
#66 - reports the same error as this one
#69 - shows the error which results from hacking around this issue, by changing import paths in index.d.ts to '../dist/CheckBox.ios'; rather than '../js/CheckBox.'

**Comment by nicholaslee119** [comment]
Sorry for the delay, 0.5.2 was just released to fix this bug

**Comment by rectified95** [comment]
@nicholaslee119 Your fix doesn't do remove the problem, as it only corrects the import paths for the type definition file. The remaining errors occur because after upgrading to the types weren't updated too.
![image](https://user-images.githubusercontent.com/12816515/92791922-f2da6e00-f361-11ea-9397-cba4f86b99e3.png)
I'm working on a fix, but I don't have much more time to spend on this. Will let you know if I manage to solve it.

**Comment by nicholaslee119** [comment]
Thanks for your report, This is a bug that happened in RN 0.62+, and We will fix it in a few days

**Comment by nicholaslee119** [comment]
0.5.3 was just released for fixing this typing bugs

**Comment by rectified95** [comment]
That was going to be my fix. Confirming the latest release works. Thanks! I think you can close this issue @nicholaslee119

**Comment by kmelmon** [comment]
Confirmed this works in RNGallery app.  Thanks for fixing this!
