### ISSUE TITLE
How to interact with checkbox in jest test?

### ISSUE THREAD

**Issue by JanithaR** [react-native-community/react-native-checkbox#78]
I am testing with react-native-testing-library and would like to interact with a couple of checkboxes I have in one of my components.

Using `fireEvent.press(getByA11yLabel('Drivers bag'));` would throw error 

> No handler function found for event: "press"

I tried calling the onValueChange() like so `getByA11yLabel('Drivers bag').props.onValueChange();` and that would throw error 

> TypeError: Cannot read property 'nativeEvent' of undefined

All I'm interested in testing is whether an effect would run when the user toggles the checkbox.

**Comment by nicholaslee119** [comment]
https://github.com/react-native-community/react-native-checkbox/blob/223e604f4fbe1abd57a476d743d294f6de82a38a/example/AppFunction.tsx#L25-L86

There are some examples to show how to change the value of checkbox outside. Please feel free to let us know if you have any trouble in the test of checkbox

**Comment by Selfmade-RuLeZ** [comment]
do you still need a better implementation as a new Button just for testing? This is how I solved it: 

``` 
it('performs onValueChange', () => {
  const func = jest.fn();
  const {getByTestId} = render(
    <CheckBox onValueChange={func} testID="myTest" />,
  );
  const checkBox = getByTestId('myTest');
  fireEvent(checkBox, 'onValueChange', {nativeEvent: {}});
  expect(func).toBeCalledTimes(1);
});


it('changes value', () => {
  let checked = false;
  const {getByTestId} = render(
    <CheckBox
      value={checked}
      onValueChange={() => (checked = !checked)}
      testID="myTest"
    />,
  );
  const checkBox = getByTestId('myTest');
  expect(checked).toBeFalsy();
  fireEvent(checkBox, 'onValueChange', {nativeEvent: {}});
  expect(checked).toBeTruthy();
});
```

The last one is not that much beauty, maybe someone can beautify it a little bit 👍

**Comment by JanithaR** [comment]
I went ahead with wrapping the label with a TouchableOpacity and testing the `onPress` callback on that.

**Comment by echase03** [comment]
Had a similar issue, ended up using this to toggle the checkbox:

`fireEvent(getByRole('checkbox'), 'onValueChange', true)`

Just wanted to add this in case it helps anybody else!

**Comment by anabeatrizzz** [comment]
> Had a similar issue, ended up using this to toggle the checkbox:
> 
> `fireEvent(getByRole('checkbox'), 'onValueChange', true)`
> 
> Just wanted to add this in case it helps anybody else!

Thanks @echase03!

I would like to add also that in my case, I needed to add an `await`

```typescript
const checkbox = await findByRole('checkbox');
fireEvent(checkbox, 'onValueChange', true);
```

**Comment by tejas-encora** [comment]
in this test how can i test the checked property on click: import {
  render,
  screen,
  fireEvent,
  cleanup,
  waitFor,
} from "@testing-library/react";
import { axe } from "vitest-axe";
import { Checkbox } from "@components/Checkbox";

// clean up mocks after each test
afterEach(() => {
  cleanup();
});

describe("Checkbox", () => {
  it("should render the checkbox and label", () => {
    const { getByRole, getByText } = render(
      <Checkbox label="Test Checkbox" onChange={() => {}} />,
    );
    expect(getByRole("checkbox")).toBeInTheDocument();
    expect(getByText("Test Checkbox")).toBeInTheDocument();
  });

  it("should call the onChange handler when clicked", async () => {
    waitFor(() => {
      const checkbox = screen.getByRole("checkbox");
      fireEvent(checkbox, "onChange");
    });
  });

  it("should show the check icon when checked", () => {
    const { getByRole, container } = render(
      <Checkbox label="Test Checkbox" checked />,
    );
    fireEvent.click(getByRole("checkbox"));
    expect(container.querySelector("svg")).toBeInTheDocument();
  });
});
