### ISSUE TITLE
Resize the CheckBox

### ISSUE THREAD

**Issue by SyedShahbazHussain** [react-native-community/react-native-checkbox#83]
# Question
Is there any props to change the size of the checkbox? Because the size of the checkbox in ios is bigger as compared to android, and want to change the size of the checkbox.

**Comment by SyedShahbazHussain** [comment]
I found the solution to just given the style.
`style={{ width: 100, height: 100}}`

**Comment by filiptdz** [comment]
For anyone who has an issue resizing the checkbox in the future, it doesn't seem to update using fast refresh. Do a hard refresh when you change the width or height, and it should update correctly.

**Comment by namlq93** [comment]
> For anyone who has an issue resizing the checkbox in the future, it doesn't seem to update using fast refresh. Do a hard refresh when you change the width or height, and it should update correctly.
not working with me even I reload the app.
![image](https://user-images.githubusercontent.com/41458989/167309097-a05cb187-ed6f-40e3-a498-ab583b57b894.png)
